---
- name: Main bootstrap. Grafana, Prometheus
  hosts: web
  remote_user: ubuntu
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      filename: grafana
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started

  - name: Download Prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
  - name: Extract Prom Resources
    ansible.builtin.unarchive:
      remote_src: true
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
  - name: Add Prom Group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: Create Prom User
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  - name: Create Prom Directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus
  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      mode: '0755'
      owner: prometheus
      group: prometheus
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries
  - name: Prometheus config file
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
  - name: Create systemd file
    ansible.builtin.template:
      src: prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service
  - name: Start Prometheus service
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: prometheus
      daemon_reload: yes


  # - name: Create Prom Group
  # - name: Create Prom User
  # - name: Create Prom Directories
  # - name: Setting Permissions
  # - name: Copy Files /usr/bin
  # - name: Copy Files /etc/prometheus
  # - name: Create Prometheus config file
  # - name: Create SystemD File 
  # - name: Ensure Prometheus is started with systemd



# Some resources used: 
# https://linoxide.com/install-prometheus-ubuntu/

# wget https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
# tar xvf prom*
# cd prometheus

# groupadd --system prometheus
# grep prometheus /etc/group

# useradd -s /sbin/nologin -r -g prometheus prometheus
# id prometheus

# mkdir -p /etc/prometheus/{rules,rules.d,files_sd}  /var/lib/prometheus

# cp prometheus promtool /usr/local/bin/
# ls /usr/local/bin/

# cp -r consoles/ console_libraries/ /etc/prometheus/

# vim /etc/systemd/system/prometheus.service

# [Unit]
# Description=Prometheus systemd service unit
# Wants=network-online.target
# After=network-online.target

# [Service]
# Type=simple
# User=prometheus
# Group=prometheus
# ExecReload=/bin/kill -HUP $MAINPID
# ExecStart=/usr/local/bin/prometheus \
# --config.file=/etc/prometheus/prometheus.yml \
# --storage.tsdb.path=/var/lib/prometheus \
# --web.console.templates=/etc/prometheus/consoles \
# --web.console.libraries=/etc/prometheus/console_libraries \
# --web.listen-address=0.0.0.0:9090

# SyslogIdentifier=prometheus
# Restart=always